# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1ee4365e98600b8c4178781dbf03c78fa0f5dffacbaa32edc686812d70784e7f98a303f22a7703e1ff186918617f899b661277e9e5374d4f83ffd09844aae68

test:
  secret_key_base: e8310e1aa14ab57fdc9e6de1eab90256e346c0ecb1c60d1c7a07a141e16f4ce57979ce7b6c591238708a1300e255ff39ddd0afda3f09e28bdf252f452547aa0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
